permission_mode: default

compaction:
  auto: true
  provider: openai
  model: qwen3.6-35b

providers:
  openai:
    type: openai
    url: https://api.openai.com/v1
    api_key: ${API_KEY}
    request_timeout: 2m
    models:
      qwen3.6-35b:
        context_window_tokens: 122880
        max_output_tokens: 66560
